name: dwf_filter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python and base packages
  - python=3.10.9
  
  # Core Python packages
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - pysam>=0.23.0
  - joblib=1.2.0
  - xgboost=1.7.4
  - pyyaml
  - pathlib
  - typing
  
  # R and R packages
  - r-base
  - r-essentials
  - r-readr
  - r-dplyr
  - r-ggplot2
  - r-forcats
  - r-proc
  - r-boot
  - r-patchwork
  - r-ggpubr

variables:
  R_LIBS_USER: ${CONDA_PREFIX}/lib/R/library