logistic_regression:
  class_weight: ['balanced']
  feature_subset: ['all']
  C: [0.1, 1, 1.3, 1.5, 2]
  max_iter: [10000]
  penalty: ['l1', 'elasticnet', 'l2']

xgboost:
  class_weight: ['balanced']
  feature_subset: ['all']
  n_estimators: [200, 250]
  max_depth: [8, 9]
  learning_rate: [0.2, 0.3]
  colsample_bytree: [0.8]

lightgbm:
  feature_subset: ['all']
  class_weight: ['balanced']
  n_estimators: [12, 25, 50, 100]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.2, 0.5, 0.9]
  colsample_bytree: [0.8]

random_forest:
  feature_subset: ['all']
  class_weight: ['balanced']
  n_estimators: [150, 200]
  max_depth: [12, 14, 16]
  min_samples_leaf: [8]

gmm:
  feature_subset: ['normal_loose']
  class_weight: ['balanced']
  n_components: [1, 2, 4, 6, 8, 10, 12]
  covariance_type: ['full']

# Cross-validation settings
cv_settings:
  outer_folds: 10
  inner_folds: 5
  repetitions: 5
  random_seed: 2

# Default dataset paths
dataset_paths:
  snv: ""
  indel: ""
  all: ""