logistic_regression:
  params:
    feature_subset: ['all']
    C: [0.1, 1, 1.3, 1.5, 2, 10, 50]
    max_iter: [10000]
    penalty: ['l1', 'elasticnet', 'l2']
  init_params:
    class_weight: 'balanced'
    transformation: 'standard'

xgboost:
  params:
    feature_subset: ['all']
    max_depth: [3, 5, 7]
    learning_rate: [0.1, 0.2, 0.3]
    colsample_bytree: [0.65, 0.7, 0.8, 0.9]
  init_params:
    class_weight: 'balanced'
    transformation: 'standard'

random_forest:
  params:
    feature_subset: ['all']
    n_estimators: [100]
    max_depth: [12]
    min_samples_leaf: [1]
  init_params:
    class_weight: 'balanced'
    transformation: 'standard'

gmm:
  params:
    feature_subset: ['all']
    n_components: [3, 4, 5]
    covariance_type: ['full']
  init_params:
    transformation: 'standard'